<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>spektra-cli</AssemblyName>
    <RootNamespace>Spektra.Cli</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spektra.Core\Spektra.Core.csproj" />
  </ItemGroup>

</Project>
